kind: pipeline
name: Django scan models

steps:
  - name: test
    image: python:3.6
    commands:
      - pip install poetry
      - poetry install
      - poetry config virtualenvs.create false
      - poetry install --no-interaction
      - python manage.py test
