kind: pipeline
name: Django scan models

steps:
  - name: test
    image: python:3.6
    commands:
      - pip install poetry
      - poetry install
      - poetry shell
      - python manage.py test
